import { StyleSheet } from 'react-native';
import { colors } from './colors';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  screen: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  header: {
    minHeight: 58,
    paddingHorizontal: 18,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(114, 120, 126, 0.18)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surface,
  },
  headerSide: {
    width: 82,
    justifyContent: 'center',
  },
  headerRight: {
    alignItems: 'flex-end',
  },
  logo: {
    color: colors.secondary,
    fontSize: 22,
    fontWeight: '800',
  },
  headerAction: {
    color: colors.primary,
    fontWeight: '800',
  },
  iconButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconText: {
    color: colors.primary,
    fontSize: 34,
    lineHeight: 34,
  },
  content: {
    padding: 18,
    gap: 16,
  },
  contentWithFooter: {
    padding: 18,
    paddingBottom: 130,
    gap: 16,
  },
  contentWithNav: {
    padding: 18,
    paddingBottom: 150,
    gap: 16,
  },
  contentWithNavAndFooter: {
    padding: 18,
    paddingBottom: 240,
    gap: 16,
  },
  centerContent: {
    padding: 18,
    paddingBottom: 80,
    gap: 16,
    justifyContent: 'center',
  },
  loginHero: {
    height: 310,
    justifyContent: 'flex-end',
    padding: 20,
  },
  countdownHero: {
    height: 260,
    justifyContent: 'flex-end',
    padding: 20,
  },
  revealHero: {
    height: 390,
    justifyContent: 'flex-end',
    padding: 20,
  },
  feedbackHero: {
    height: 250,
    justifyContent: 'flex-end',
    padding: 20,
    marginHorizontal: -18,
  },
  giftHero: {
    height: 320,
    justifyContent: 'flex-end',
    padding: 20,
  },
  heroImage: {
    borderRadius: 18,
  },
  imageOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 26, 43, 0.42)',
    borderRadius: 18,
  },
  heroKicker: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '700',
  },
  heroTitle: {
    color: colors.white,
    fontSize: 29,
    lineHeight: 35,
    fontWeight: '900',
  },
  title: {
    color: colors.primary,
    fontSize: 30,
    lineHeight: 36,
    fontWeight: '900',
  },
  successTitle: {
    color: '#167a3f',
    fontSize: 30,
    lineHeight: 36,
    fontWeight: '900',
    textAlign: 'center',
  },
  titleSmall: {
    color: colors.primary,
    fontSize: 21,
    lineHeight: 27,
    fontWeight: '900',
  },
  titleCenter: {
    color: colors.primary,
    fontSize: 24,
    textAlign: 'center',
    fontWeight: '900',
  },
  subtitle: {
    color: colors.muted,
    fontSize: 16,
    lineHeight: 23,
  },
  separator: {
    textAlign: 'center',
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
  },
  legal: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
  },
  errorText: {
    color: '#c62828',
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 18,
    textAlign: 'center',
  },
  successText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '900',
    lineHeight: 18,
  },
  input: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    minHeight: 50,
    color: colors.text,
    fontSize: 15,
  },
  inputInline: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    minHeight: 44,
    color: colors.text,
    fontSize: 15,
  },
  inputDisplayText: {
    color: colors.text,
    fontSize: 15,
    lineHeight: 50,
  },
  inputPlaceholder: {
    color: colors.muted,
    fontSize: 15,
    lineHeight: 50,
  },
  textArea: {
    minHeight: 100,
    paddingTop: 14,
    textAlignVertical: 'top',
  },
  textAreaSmall: {
    minHeight: 76,
    paddingTop: 14,
    textAlignVertical: 'top',
  },
  button: {
    backgroundColor: colors.primary,
    borderRadius: 14,
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  buttonSecondary: {
    backgroundColor: colors.secondary,
  },
  buttonDanger: {
    backgroundColor: '#c62828',
  },
  buttonMuted: {
    backgroundColor: colors.cardMuted,
    borderWidth: 1,
    borderColor: colors.border,
  },
  buttonText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '900',
  },
  buttonTextMuted: {
    color: colors.primary,
  },
  stack: {
    gap: 10,
  },
  progressRow: {
    flexDirection: 'row',
    gap: 8,
  },
  progressBar: {
    flex: 1,
    height: 4,
    borderRadius: 8,
    backgroundColor: colors.cardMuted,
  },
  progressBarActive: {
    backgroundColor: colors.primary,
  },
  sectionTitle: {
    color: colors.primary,
    fontSize: 20,
    fontWeight: '900',
    marginTop: 8,
  },
  chipGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chip: {
    backgroundColor: colors.cardSoft,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  chipSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  chipText: {
    color: colors.primary,
    fontWeight: '800',
  },
  chipTextSelected: {
    color: colors.white,
  },
  optionRow: {
    backgroundColor: colors.cardSoft,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 14,
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  optionRowActive: {
    borderColor: colors.primary,
    backgroundColor: colors.cardMuted,
  },
  optionText: {
    color: colors.primary,
    fontSize: 16,
    fontWeight: '700',
  },
  radio: {
    color: colors.primary,
    fontSize: 18,
  },
  footerBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: 'rgba(114, 120, 126, 0.18)',
    padding: 16,
    gap: 10,
  },
  footerBarWithNav: {
    bottom: 74,
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 74,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: 'rgba(114, 120, 126, 0.18)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 6,
  },
  navItem: {
    minWidth: 62,
    height: 52,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navItemActive: {
    backgroundColor: colors.cardMuted,
  },
  navIcon: {
    color: colors.muted,
    fontSize: 17,
    fontWeight: '900',
  },
  navIconActive: {
    color: colors.primary,
  },
  navLabel: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: '700',
  },
  navLabelActive: {
    color: colors.primary,
  },
  horizontalList: {
    gap: 14,
    paddingRight: 18,
  },
  carouselList: {
    gap: 14,
    paddingRight: 18,
  },
  carouselDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginTop: -4,
  },
  carouselDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.border,
  },
  carouselDotActive: {
    width: 22,
    backgroundColor: colors.secondary,
  },
  featuredCard: {
    width: 290,
    gap: 10,
  },
  featuredImage: {
    height: 390,
    justifyContent: 'flex-end',
    padding: 18,
  },
  planTag: {
    alignSelf: 'flex-start',
    backgroundColor: colors.secondary,
    color: colors.white,
    fontSize: 11,
    fontWeight: '900',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    overflow: 'hidden',
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  featuredTitle: {
    color: colors.white,
    fontSize: 26,
    lineHeight: 31,
    fontWeight: '900',
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  meta: {
    color: colors.muted,
    fontSize: 13,
  },
  price: {
    color: colors.primary,
    fontSize: 16,
    fontWeight: '900',
  },
  link: {
    color: colors.secondary,
    fontWeight: '900',
  },
  linkCenter: {
    color: colors.secondary,
    fontWeight: '900',
    textAlign: 'center',
    paddingVertical: 10,
  },
  card: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: 'rgba(114, 120, 126, 0.16)',
    borderRadius: 14,
    padding: 16,
    gap: 8,
  },
  cardDark: {
    backgroundColor: colors.primary,
  },
  cardTitle: {
    color: colors.primary,
    fontSize: 16,
    fontWeight: '900',
  },
  cardText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  experienceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  thumb: {
    width: 92,
    height: 92,
    borderRadius: 12,
    backgroundColor: colors.cardMuted,
  },
  flex: {
    flex: 1,
  },
  rating: {
    color: colors.secondary,
    fontWeight: '900',
    marginTop: 5,
  },
  floatingCta: {
    position: 'absolute',
    left: 18,
    right: 18,
    bottom: 88,
  },
  innerGap: {
    gap: 12,
    marginTop: 12,
  },
  budgetInputs: {
    flexDirection: 'row',
    gap: 12,
  },
  budgetInputGroup: {
    flex: 1,
    gap: 6,
  },
  budgetSlider: {
    height: 42,
    justifyContent: 'center',
    marginTop: 4,
  },
  budgetTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: colors.cardMuted,
  },
  budgetTrackActive: {
    position: 'absolute',
    height: 8,
    borderRadius: 999,
    backgroundColor: colors.secondary,
  },
  budgetThumb: {
    position: 'absolute',
    width: 24,
    height: 24,
    marginLeft: -12,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 4,
    borderColor: colors.secondary,
  },
  calendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  calendarArrow: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  calendarWeekDay: {
    width: '12.6%',
    textAlign: 'center',
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
  },
  calendarDay: {
    width: '12.6%',
    aspectRatio: 1,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.cardSoft,
  },
  calendarDaySelected: {
    backgroundColor: colors.secondary,
  },
  calendarDayDisabled: {
    opacity: 0.35,
  },
  calendarDayText: {
    color: colors.primary,
    fontWeight: '800',
  },
  calendarDayTextDisabled: {
    color: colors.muted,
  },
  calendarDayTextSelected: {
    color: colors.surface,
  },
  kicker: {
    color: colors.secondary,
    textTransform: 'uppercase',
    letterSpacing: 1,
    fontSize: 12,
    fontWeight: '900',
  },
  kickerCenter: {
    color: colors.secondary,
    textTransform: 'uppercase',
    letterSpacing: 1,
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'center',
  },
  paymentImage: {
    width: 112,
    height: 150,
    borderRadius: 14,
    backgroundColor: colors.cardMuted,
  },
  ticketSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  ticketStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  stepperButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.secondary,
  },
  stepperButtonText: {
    color: colors.surface,
    fontSize: 20,
    fontWeight: '900',
  },
  ticketCount: {
    minWidth: 24,
    textAlign: 'center',
    color: colors.primary,
    fontSize: 18,
    fontWeight: '900',
  },
  removeSelector: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.card,
  },
  removeSelectorText: {
    color: colors.secondary,
    fontSize: 16,
    fontWeight: '900',
  },
  paymentMethodRow: {
    flexDirection: 'row',
    gap: 10,
  },
  paymentMethodButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.cardSoft,
  },
  paymentMethodButtonActive: {
    backgroundColor: colors.secondary,
    borderColor: colors.secondary,
  },
  paymentMethodText: {
    color: colors.primary,
    fontWeight: '900',
  },
  paymentMethodTextActive: {
    color: colors.surface,
  },
  cardFieldsRow: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
  },
  cardExpirationInput: {
    flex: 1,
    justifyContent: 'center',
  },
  cardSecurityInput: {
    width: 96,
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    minHeight: 44,
    color: colors.text,
    fontSize: 15,
  },
  expirationPicker: {
    gap: 12,
    padding: 12,
    borderRadius: 12,
    backgroundColor: colors.cardSoft,
  },
  expirationYearGroup: {
    gap: 8,
  },
  expirationMonthButton: {
    minWidth: 42,
    minHeight: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
  },
  expirationMonthButtonActive: {
    backgroundColor: colors.secondary,
    borderColor: colors.secondary,
  },
  expirationMonthText: {
    color: colors.primary,
    fontWeight: '900',
  },
  expirationMonthTextActive: {
    color: colors.surface,
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: 6,
  },
  paymentText: {
    color: colors.muted,
    fontSize: 15,
  },
  accentText: {
    color: colors.secondary,
  },
  paymentStrong: {
    color: colors.primary,
    fontWeight: '900',
    fontSize: 18,
  },
  successBox: {
    alignItems: 'center',
    gap: 12,
    paddingVertical: 20,
  },
  successIcon: {
    width: 150,
    height: 150,
    borderRadius: 38,
    backgroundColor: colors.card,
    color: colors.secondary,
    borderWidth: 1,
    borderColor: colors.border,
    textAlign: 'center',
    textAlignVertical: 'center',
    fontSize: 70,
  },
  trumpetBadge: {
    width: 150,
    height: 150,
    borderRadius: 38,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  trumpetBadgeSuccess: {
    backgroundColor: '#e8f7ee',
    borderColor: '#167a3f',
  },
  trumpetIcon: {
    fontSize: 76,
  },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: colors.cardMuted,
    overflow: 'hidden',
  },
  progressFill: {
    width: '34%',
    height: 8,
    backgroundColor: colors.secondary,
  },
  progressFillSuccess: {
    backgroundColor: '#167a3f',
  },
  timerRow: {
    flexDirection: 'row',
    gap: 10,
  },
  timerBox: {
    flex: 1,
    backgroundColor: colors.primary,
    borderRadius: 16,
    paddingVertical: 18,
    alignItems: 'center',
  },
  timerValue: {
    color: colors.white,
    fontSize: 34,
    fontWeight: '900',
  },
  timerAccent: {
    color: '#ffb4a8',
  },
  timerLabel: {
    color: 'rgba(255,255,255,0.68)',
    fontSize: 10,
    textTransform: 'uppercase',
    fontWeight: '900',
  },
  twoColumns: {
    flexDirection: 'row',
    gap: 12,
  },
  whiteMeta: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: 13,
  },
  starsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  star: {
    color: colors.border,
    fontSize: 42,
  },
  starActive: {
    color: colors.secondary,
  },
  packCard: {
    width: 250,
    minHeight: 190,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    padding: 16,
    gap: 10,
  },
  packCardActive: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.secondary,
  },
  packPrice: {
    color: colors.primary,
    fontSize: 26,
    fontWeight: '900',
  },
  selectText: {
    color: colors.primary,
    fontWeight: '900',
    marginTop: 'auto',
  },
  whiteText: {
    color: colors.white,
  },
  whiteSoft: {
    color: 'rgba(255,255,255,0.74)',
  },
  ticketTitle: {
    color: colors.white,
    fontSize: 24,
    fontWeight: '900',
    textAlign: 'center',
  },
  ticketCode: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 14,
    marginTop: 12,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 26, 43, 0.48)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  modalCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: colors.card,
    borderRadius: 16,
    padding: 18,
    gap: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
});
